// GlucoDefense — Patient definitions

export const PATIENTS = [
  {
    id: 'healthy',
    name: 'Healthy Person',
    emoji: '\u{1F3C3}',
    color: '#2ECC71',
    description: 'Normal metabolism, no medications needed.',
    physiology: {
      startingDegradation: 0,
      insulinProductionRate: 1.5,
      insulinSensitivity: 1.0,
      degradationEnabled: false,
      liverStorageMultiplier: 1.5,
      energyStartMultiplier: 1.5,
      energyDrainMultiplier: 0.3,
      rebelDamageMultiplier: 0.1,
      kidneyAutoFilterRate: 2.0,
      insulinCharges: null, // unlimited (cooldown-based)
    },
    availableInterventions: ['walk', 'exercise'],
    days: [
      { dayId: 1, levelRef: 1, name: 'Day 1: Normal Day',
        narrative: 'A regular weekday. Wake up, have breakfast, head to work, eat lunch, come home for dinner. Your healthy body handles everything on autopilot.' },
      { dayId: 2, levelRef: 2, name: 'Day 2: Office Lunch',
        narrative: 'Colleagues brought donuts to the office, and lunch is catered pizza. Temptations everywhere, but your metabolism can handle the load.' },
      { dayId: 3, levelRef: 3, name: 'Day 3: Birthday',
        narrative: 'It\'s your friend\'s birthday! Cake, snacks, and sweets all evening. Even a healthy body gets tested by a sugar avalanche.' },
      { dayId: 4, levelRef: 4, name: 'Day 4: Weekend',
        narrative: 'Lazy Saturday. Late brunch, afternoon snacking, big dinner out. No routine means meals come at unpredictable times.' },
      { dayId: 5, levelRef: 5, name: 'Day 5: Stress',
        narrative: 'A stressful day — deadlines, skipped meals, then stress-eating at night. Cortisol adds extra glucose to the mix.' },
    ],
  },
  {
    id: 'type1',
    name: 'Type 1 Diabetes',
    emoji: '\u{1F489}',
    color: '#3498DB',
    description: 'No insulin production. Must inject insulin.',
    physiology: {
      startingDegradation: 0,
      insulinProductionRate: 0.05,
      insulinSensitivity: 1.0,
      degradationEnabled: false,
      liverStorageMultiplier: 1.0,
      energyStartMultiplier: 1.0,
      energyDrainMultiplier: 1.0,
      rebelDamageMultiplier: 0.7,
      kidneyAutoFilterRate: 1.5,
      insulinCharges: 15, // limited insulin injections
    },
    availableInterventions: ['walk', 'exercise', 'insulin'],
    days: [
      { dayId: 1, levelRef: 1, name: 'Day 1: First Injections',
        narrative: 'Your pancreas produces almost no insulin. Every meal requires a carefully timed injection. Start simple — learn the basics.' },
      { dayId: 2, levelRef: 2, name: 'Day 2: Counting Carbs',
        narrative: 'Time to match insulin doses to carb counts. Too little insulin means high BG; too much means dangerous lows. Find the balance.' },
      { dayId: 3, levelRef: 3, name: 'Day 3: Party Challenge',
        narrative: 'Birthday party with unpredictable food. Estimating carbs in cake and snacks is tricky. Pre-bolus or correct after? Your call.' },
      { dayId: 4, levelRef: 4, name: 'Day 4: Active Day',
        narrative: 'A day of exercise and activity. Physical activity acts like extra insulin — watch for lows! You may need less insulin today.' },
      { dayId: 5, levelRef: 5, name: 'Day 5: Fine Tuning',
        narrative: 'Complex day with varied meals and activity. Master the timing of insulin doses to stay in range all day. Every unit counts.' },
    ],
  },
  {
    id: 'type2',
    name: 'Type 2 Diabetes',
    emoji: '\u{1FA7A}',
    color: '#F39C12',
    description: 'Insulin resistance develops over time.',
    physiology: {
      startingDegradation: 0,
      insulinProductionRate: 1.0,
      insulinSensitivity: 1.0,
      degradationEnabled: true,
      liverStorageMultiplier: 1.0,
      energyStartMultiplier: 1.0,
      energyDrainMultiplier: 1.0,
      rebelDamageMultiplier: 1.0,
      kidneyAutoFilterRate: 1.5,
      insulinCharges: null,
    },
    availableInterventions: ['walk', 'exercise', 'semaglutide', 'metformin', 'dapagliflozin'],
    days: [
      { dayId: 1, levelRef: 1, name: 'Day 1: Diagnosis',
        narrative: 'Just diagnosed with Type 2 diabetes. Your body still produces insulin, but cells are starting to resist it. Choose meals wisely.' },
      { dayId: 2, levelRef: 2, name: 'Day 2: Office Lunch',
        narrative: 'Office catering is carb-heavy. Medications can help, but food choices matter most. Can you pick the healthier options?' },
      { dayId: 3, levelRef: 3, name: 'Day 3: Birthday Party',
        narrative: 'Social pressure to eat cake and treats. Every sugary food pushes your resistance higher. Use medications and walks strategically.' },
      { dayId: 4, levelRef: 4, name: 'Day 4: Weekend',
        narrative: 'Weekend without routine. Irregular meals cause unpredictable spikes. Plan ahead or react quickly — either way, stay in control.' },
      { dayId: 5, levelRef: 5, name: 'Day 5: Management',
        narrative: 'Full day of managing diabetes with diet, exercise, and medications. Show that you understand the disease and can keep BG stable.' },
    ],
  },
  {
    id: 'type2advanced',
    name: 'Type 2 Advanced',
    emoji: '\u26A0\uFE0F',
    color: '#E74C3C',
    description: 'Significant organ degradation already present.',
    physiology: {
      startingDegradation: 2,
      insulinProductionRate: 0.7,
      insulinSensitivity: 0.6,
      degradationEnabled: true,
      liverStorageMultiplier: 0.8,
      energyStartMultiplier: 0.8,
      energyDrainMultiplier: 1.0,
      rebelDamageMultiplier: 1.5,
      kidneyAutoFilterRate: 0.8,
      insulinCharges: null,
    },
    availableInterventions: ['walk', 'exercise', 'semaglutide', 'metformin', 'dapagliflozin'],
    days: [
      { dayId: 1, levelRef: 1, name: 'Day 1: Complications',
        narrative: 'Years of high blood sugar have damaged your organs. Kidneys are weaker, insulin resistance is high. Even small meals cause big spikes.' },
      { dayId: 2, levelRef: 2, name: 'Day 2: Diet Change',
        narrative: 'Doctor ordered a strict diet change. Focus on slow-absorbing foods and use all available medications. Your weakened body has little margin for error.' },
      { dayId: 3, levelRef: 3, name: 'Day 3: Strict Control',
        narrative: 'Every meal must be carefully planned. High BG damages organs further, but going too low is equally dangerous. Precision is everything.' },
      { dayId: 4, levelRef: 4, name: 'Day 4: Emergency',
        narrative: 'A difficult day with challenging meals. Your degraded organs struggle to process glucose. Use every tool at your disposal to survive.' },
      { dayId: 5, levelRef: 5, name: 'Day 5: Survival',
        narrative: 'The ultimate test. Damaged organs, resistant cells, complex meals. Can you maintain control despite severe metabolic dysfunction?' },
    ],
  },
];

export function getPatient(id) {
  return PATIENTS.find(p => p.id === id) || null;
}
